# 站点基本信息
title: "Jiaqi Liao - Academic Website"  # 网站标题
email: liaojq@ruc.edu.cn         # 您的邮箱
description: >                         # 网站描述（用于SEO）
  Personal academic website of Jiaqi Liao, 
  PhD Candidate in Economics.
baseurl: ""                           # 如果站点不在根目录，填写子路径
url: "https://github.com/jiaqiliao6/jiaqiliao.github.io"      # 替换为您的GitHub Pages网址
timezone: Asia/Bei_jing              # 时区设置

# 构建设置
markdown: kramdown                    # 使用的Markdown解析器
theme: minima                         # 使用的基本主题（可选）
plugins:                              # 使用的Jekyll插件
  - jekyll-feed

# 作者信息
author:
  name: "Jiaqi Liao"
  position: "PhD Candidate"
  university: "Renmin University of China"
  department: "Department of Economics"

# 导航链接
navigation:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research.html"
  - name: "Teaching"
    link: "/teaching.html"

# 自定义变量（供模板使用）
cv_link: "/assets/cv.pdf"                     # CV文件路径
