# === 需要自定义的部分 ===
title: "您的姓名 - 学术主页"  # 修改为您的姓名
email: your.email@example.com  # 修改为您的邮箱
url: "https://yourusername.github.io"  # 修改为您的GitHub用户名

author:
  name: "Jiaqi Liao"  # 修改为您的姓名
  position: "Phd Candidate"  # 例如: "Assistant Professor"
  university: "Renmin University of China"  # 例如: "The Chinese University of Hong Kong"
  department: "Department of Economics"  # 例如: "Department of Economics"
  #affiliation: ""  # 例如: "Associate Member, University of Oxford"
# === 结束自定义部分 ===

# 以下内容通常不需要修改
description: >
  Personal academic website of Jiaqi Liao
baseurl: ""
timezone: Asia/Hong_Kong

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

navigation:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research.html"
  - name: "Teaching"
    link: "/teaching.html"

cv_link: "/cv.pdf"
