title: "Jiaqi Liao"
description: "PhD Candidate in Economics"
url: "https://jiaqiliao6.github.io"
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
