# === 需要自定义的部分 ===
url: "https://jiaqiliao6.github.io/"  # 修改为您的GitHub用户名


# === 结束自定义部分 ===

# 以下内容通常不需要修改

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

navigation:
  - name: "Home"
    link: "/index.html"
  - name: "Research"
    link: "/research.html"
  - name: "Teaching"
    link: "/teaching.html"

cv_link: "/cv.pdf"
